Repository baking-bad/pytezos, pull requests merged in 2024-02, with the labels that each got.

#356 Update to Oxfordnet and Octez 19.0
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  requirements.dev.txt
  requirements.slim.txt
  requirements.txt
  src/michelson_kernel/docs.py
  src/michelson_kernel/kernel.py
  src/pytezos/block/header.py
  src/pytezos/context/mixin.py
  src/pytezos/sandbox/node.py
  src/pytezos/sandbox/parameters.py
  tests/integration_tests/test_metadata.py
  tests/sandbox_tests/test_sandbox.py
  tests/sandbox_tests/test_wait_helper.py
Labels: ✨ feature

#358 Add forging/encoding for smart rollup state hash
  CHANGELOG.md
  Makefile
  src/pytezos/crypto/encoding.py
  tests/unit_tests/test_crypto/test_encoding.py
Labels: 🧹 chore

#361 Fixed protocol parameters for sandboxed node
  CHANGELOG.md
  README.md
  poetry.lock
  requirements.dev.txt
  requirements.slim.txt
  requirements.txt
  src/pytezos/cli/cli.py
  src/pytezos/sandbox/node.py
  src/pytezos/sandbox/parameters.py
  tests/sandbox_tests/test_sandbox.py
  tests/sandbox_tests/test_wait_helper.py
Labels: bug

#362 Update cryptographic libraries
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  requirements.dev.txt
  requirements.slim.txt
  requirements.txt
Labels: bug
